# Generated by Django 6.0.3 on 2026-03-18 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('produto_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=155)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=13)),
                ('estoque', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentagem_desconto', models.IntegerField(blank=True, null=True)),
                ('vigencia_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigencia_fim', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='produtos.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
